/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    members: MemberAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    members: Member;
    'installation-state': InstallationState;
    'audit-logs': AuditLog;
    'plugin-states': PluginState;
    'commerce-customers': CommerceCustomer;
    'commerce-orders': CommerceOrder;
    forms: Form;
    'form-submissions': FormSubmission;
    media: Media;
    pages: Page;
    posts: Post;
    redirects: Redirect;
    'webhook-subscriptions': WebhookSubscription;
    'webhook-deliveries': WebhookDelivery;
    integrations: Integration;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    'installation-state': InstallationStateSelect<false> | InstallationStateSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'plugin-states': PluginStatesSelect<false> | PluginStatesSelect<true>;
    'commerce-customers': CommerceCustomersSelect<false> | CommerceCustomersSelect<true>;
    'commerce-orders': CommerceOrdersSelect<false> | CommerceOrdersSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'webhook-subscriptions': WebhookSubscriptionsSelect<false> | WebhookSubscriptionsSelect<true>;
    'webhook-deliveries': WebhookDeliveriesSelect<false> | WebhookDeliveriesSelect<true>;
    integrations: IntegrationsSelect<false> | IntegrationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Member;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface MemberAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'super-admin' | 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  firstName: string;
  lastName?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'members';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "installation-state".
 */
export interface InstallationState {
  id: number;
  key: string;
  status: 'installed';
  siteName: string;
  adminEmail: string;
  installedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  action: string;
  actorUser?: (number | null) | User;
  actorEmail?: string | null;
  actorRole?: ('super-admin' | 'admin' | 'editor') | null;
  actorSource: 'system' | 'user' | 'anonymous';
  targetCollection?: string | null;
  targetId?: string | null;
  result: 'success' | 'failure';
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  occurredAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugin-states".
 */
export interface PluginState {
  id: number;
  pluginId: string;
  pluginVersion: string;
  enabled: boolean;
  enabledModules?:
    | {
        moduleId: string;
        id?: string | null;
      }[]
    | null;
  activatedAt?: string | null;
  activatedBy?: (number | null) | User;
  deactivatedAt?: string | null;
  deactivatedBy?: (number | null) | User;
  migrations?:
    | {
        migrationId: string;
        version: string;
        name: string;
        description: string;
        destructive: boolean;
        status: 'pending' | 'applied';
        executedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commerce-customers".
 */
export interface CommerceCustomer {
  id: number;
  provider: 'medusa';
  member: number | Member;
  email: string;
  externalCustomerId: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commerce-orders".
 */
export interface CommerceOrder {
  id: number;
  provider: 'medusa';
  externalOrderId: string;
  externalCartId?: string | null;
  member?: (number | null) | Member;
  customerEmail: string;
  externalCustomerId?: string | null;
  status: 'draft' | 'open' | 'placed' | 'fulfilled';
  currencyCode: string;
  subtotalAmount: number;
  totalAmount: number;
  paymentMode: 'test';
  placedAt: string;
  /**
   * Safe order snapshot recorded at test checkout time.
   */
  lineItems?:
    | {
        productExternalId: string;
        variantExternalId: string;
        title: string;
        quantity: number;
        unitAmount: number;
        totalAmount: number;
        currencyCode: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  /**
   * Lowercase alphanumeric and hyphens only. Used to embed this form in pages.
   */
  slug: string;
  description?: string | null;
  /**
   * Define the form fields. Field IDs must be unique and lowercase.
   */
  fields: {
    /**
     * Unique field identifier — lowercase alphanumeric and underscores.
     */
    id: string;
    type: 'text' | 'textarea' | 'email' | 'checkbox' | 'select' | 'hidden';
    label: string;
    placeholder?: string | null;
    required?: boolean | null;
    /**
     * Only applicable for hidden fields. Value set server-side.
     */
    defaultValue?: string | null;
    /**
     * Required for select fields.
     */
    options?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
  }[];
  /**
   * Workflow actions to execute when this form is submitted.
   */
  actions?:
    | {
        type: 'email' | 'webhook';
        /**
         * HTTPS webhook URL. Must use https:// scheme.
         */
        webhookUrl?: string | null;
        /**
         * Recipient email for email notification.
         */
        emailTo?: string | null;
        /**
         * Recipient display name.
         */
        emailToName?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  formSlug: string;
  /**
   * Validated field values. Read-only after submission.
   */
  fields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  submittedAt: string;
  status: 'received' | 'processed' | 'failed';
  /**
   * Safe workflow execution metadata. Does not contain secrets or webhook responses.
   */
  workflowResults?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  publishedAt?: string | null;
  excerpt?: string | null;
  heroImage?: (number | null) | Media;
  /**
   * Public content is anonymous-safe. Members-only content requires a signed-in member session.
   */
  accessLevel: 'public' | 'members';
  body: string;
  /**
   * Optional versioned NexPress builder document JSON. Public rendering falls back to body when omitted or invalid.
   */
  builder?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
    noFollow?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  publishedAt?: string | null;
  excerpt?: string | null;
  featuredImage?: (number | null) | Media;
  /**
   * Public content is anonymous-safe. Members-only content requires a signed-in member session.
   */
  accessLevel: 'public' | 'members';
  body: string;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
    noFollow?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  sourcePath: string;
  destinationPath: string;
  type: '301' | '302';
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-subscriptions".
 */
export interface WebhookSubscription {
  id: number;
  name: string;
  url: string;
  /**
   * Used to sign outbound webhooks. Keep this secret.
   */
  secret?: string | null;
  events: ('form.submitted' | 'order.created' | 'order.updated' | 'page.published' | 'page.unpublished')[];
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-deliveries".
 */
export interface WebhookDelivery {
  id: number;
  subscription: number | WebhookSubscription;
  event: string;
  /**
   * Safe payload without secrets
   */
  payload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'success' | 'failed';
  statusCode?: number | null;
  responseBody?: string | null;
  errorMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations".
 */
export interface Integration {
  id: number;
  name: string;
  provider: 'medusa' | 'stripe';
  active?: boolean | null;
  /**
   * Safe configuration only. DO NOT STORE SECRETS HERE.
   */
  config?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'installation-state';
        value: number | InstallationState;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'plugin-states';
        value: number | PluginState;
      } | null)
    | ({
        relationTo: 'commerce-customers';
        value: number | CommerceCustomer;
      } | null)
    | ({
        relationTo: 'commerce-orders';
        value: number | CommerceOrder;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'webhook-subscriptions';
        value: number | WebhookSubscription;
      } | null)
    | ({
        relationTo: 'webhook-deliveries';
        value: number | WebhookDelivery;
      } | null)
    | ({
        relationTo: 'integrations';
        value: number | Integration;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'members';
        value: number | Member;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'members';
        value: number | Member;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "installation-state_select".
 */
export interface InstallationStateSelect<T extends boolean = true> {
  key?: T;
  status?: T;
  siteName?: T;
  adminEmail?: T;
  installedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  action?: T;
  actorUser?: T;
  actorEmail?: T;
  actorRole?: T;
  actorSource?: T;
  targetCollection?: T;
  targetId?: T;
  result?: T;
  metadata?: T;
  occurredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugin-states_select".
 */
export interface PluginStatesSelect<T extends boolean = true> {
  pluginId?: T;
  pluginVersion?: T;
  enabled?: T;
  enabledModules?:
    | T
    | {
        moduleId?: T;
        id?: T;
      };
  activatedAt?: T;
  activatedBy?: T;
  deactivatedAt?: T;
  deactivatedBy?: T;
  migrations?:
    | T
    | {
        migrationId?: T;
        version?: T;
        name?: T;
        description?: T;
        destructive?: T;
        status?: T;
        executedAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commerce-customers_select".
 */
export interface CommerceCustomersSelect<T extends boolean = true> {
  provider?: T;
  member?: T;
  email?: T;
  externalCustomerId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commerce-orders_select".
 */
export interface CommerceOrdersSelect<T extends boolean = true> {
  provider?: T;
  externalOrderId?: T;
  externalCartId?: T;
  member?: T;
  customerEmail?: T;
  externalCustomerId?: T;
  status?: T;
  currencyCode?: T;
  subtotalAmount?: T;
  totalAmount?: T;
  paymentMode?: T;
  placedAt?: T;
  lineItems?:
    | T
    | {
        productExternalId?: T;
        variantExternalId?: T;
        title?: T;
        quantity?: T;
        unitAmount?: T;
        totalAmount?: T;
        currencyCode?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  fields?:
    | T
    | {
        id?: T;
        type?: T;
        label?: T;
        placeholder?: T;
        required?: T;
        defaultValue?: T;
        options?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
      };
  actions?:
    | T
    | {
        type?: T;
        webhookUrl?: T;
        emailTo?: T;
        emailToName?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  formSlug?: T;
  fields?: T;
  submittedAt?: T;
  status?: T;
  workflowResults?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedAt?: T;
  excerpt?: T;
  heroImage?: T;
  accessLevel?: T;
  body?: T;
  builder?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedAt?: T;
  excerpt?: T;
  featuredImage?: T;
  accessLevel?: T;
  body?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  sourcePath?: T;
  destinationPath?: T;
  type?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-subscriptions_select".
 */
export interface WebhookSubscriptionsSelect<T extends boolean = true> {
  name?: T;
  url?: T;
  secret?: T;
  events?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-deliveries_select".
 */
export interface WebhookDeliveriesSelect<T extends boolean = true> {
  subscription?: T;
  event?: T;
  payload?: T;
  status?: T;
  statusCode?: T;
  responseBody?: T;
  errorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations_select".
 */
export interface IntegrationsSelect<T extends boolean = true> {
  name?: T;
  provider?: T;
  active?: T;
  config?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}